### ISSUE TITLE
Zig mutex API has changed

### ISSUE THREAD

**Issue by ceberly** [jamii/focus#1]
Feel free to ignore this, but in my attempts to get focus running on arch i noticed that focus no longer compiles with zig:master because the API for mutex aquire()/release() has changed to lock()/unlock(): 

https://github.com/nuald/zig/commit/05d247542bcc457373525c11d0957c8ef3ffbf56

I made edits here: https://github.com/ceberly/focus/commit/d036e28ff87eba57dfeb8b648d85a27324712017

and the corresponding changes in imp as well: https://github.com/ceberly/imp/commit/c6c2beaa346348e02f4840472f9ebe2f5163d963

**Comment by jamii** [comment]
Thanks, good to know for the next time I bump the zig version.

**Comment by ceberly** [comment]
cool, closing the issue.
