### ISSUE TITLE
`attempt to cast negative value to unsigned integer` + First Impressions

### ISSUE THREAD

**Issue by antler5** [jamii/focus#7]
Hi! I was inspired by your posts to check this out.

I've read the Emacs C sources, and really appreciate your "`go-to-def`-compatible control-flow" and simple, hard-coded behaviors.
I am familiar with single-user systems, and am not afraid to feel the rough edges and learn a lil' Zig in the process.

There is, of course, no documentation; but there are a few things it would have been nice to know, so for posterity:
- AFAIK files must be opened from the command-line (no scratch-buffer or find-file).
- File paths must be absolute.
- Margin features `>` / `<` scroll-indicators and `\` for line-wrapping.

My only question is:
- Pressing `Ctrl-D` causes all subsequent characters to be repeated an additional time (inc. `BKSP`, and for perpetuity). This stacks infinitely, but AFAIK can not be reset. This, uhm, may be intentional? Will read all the code and find out sooner or later.

-----

The real `Issue` is this:

``` make
warning: Frame took 129755201 ns

thread 51553 panic: attempt to cast negative value to unsigned integer
/media/zpool/focus/lib/focus/editor.zig:1105:53: 0x2f4fac in getCenterPos (focus-dev)
        const prev_center_wrapped_line = @as(usize, @intCast(@divTrunc(self.top_pixel + @divTrunc(text_rect_h, 2), self.app.atlas.char_height)));
                                                    ^
/media/zpool/focus/lib/focus/editor.zig:357:56: 0x2eb15d in frame (focus-dev)
        self.buffer.last_center_pos = self.getCenterPos(text_rect.h);
                                                       ^
/media/zpool/focus/lib/focus/project_searcher.zig:0:34: 0x2d9819 in frame (focus-dev)
/media/zpool/focus/lib/focus.zig:355:52: 0x2b2908 in run (focus-dev)
        for (current_windows) |window| window.frame();
                                                   ^
/media/zpool/focus/bin/focus.zig:0:36: 0x2afbe0 in main (focus-dev)
???:?:?: 0x7f2aafd9dfcd in ??? (libc.so.6)
Unwind information for `libc.so.6:0x7f2aafd9dfcd` was not available, trace may be incomplete
```

I'm running a NixOS LiveCD from just a few days back (`nixos-plasma5-23.11.4516.e0da498ad77a-x86_64-linux.iso`), and can reproduce the issue by attempting to scroll up past the top of a file (with the mouse wheel, not sure how to ~move the cursor~ *scroll* with the keyboard yet *(Edit: Just figured out cursor movement.)*).

**Comment by jamii** [comment]
Well, apologies for all the terrible code you're going to read :)

In particular the rendering in editor.zig is gnarly for no good reason.

> no scratch-buffer or find-file

Ctrl-o opens files (relative to the current file) and ctrl-p does fuzzy find in the list of directories found in https://github.com/jamii/focus/blob/cc18333402154e207584ba78d186d4e5ef2de957//build.zig#L20.

> Pressing Ctrl-D causes all subsequent characters to be repeated an additional time

This is multi-cursor-next, like in sublime or vs code. It makes more sense if you select some text first. You can reset it with ctrl-q or by moving the cursor with the mouse. The cursor icon turns green when you have multiple cursors.

> can reproduce the issue by attempting to scroll up past the top of a file

I can't reproduce this, but I also don't have a scroll wheel. I wonder if the touchpad scroll is fixed to some friendly values. 

If you're on a system where rr works, would you mind capturing the bug with `rr record --wait focus`? (Building with `zig build -Doptimize=Debug` would also help).

**Comment by antler5** [comment]
> I wonder if the touchpad scroll is fixed to some friendly values.

Ah, well, my ""mouse-wheel"" just so happens to be a touch-pad-- I hadn't presumed an issue so cursed that the distinction would matter, just as I take for granted that the system image in RAM is un-corrupted, but that reasoning is sound! (*checks block device [hash](https://releases.nixos.org/nixos/23.11/nixos-23.11.4516.e0da498ad77a/nixos-plasma5-23.11.4516.e0da498ad77a-x86_64-linux.iso.sha256), reboots...* no curses there).

> zig build -Doptimize=Debug

can-do

> rr record **--wait** focus

Oh, it wasn't/doesn't return-- does that mean I should drop the `--wait`?
I still got a trace, so I'm gonna assume it's good.

[rr-trace.tar.gz](https://github.com/jamii/focus/files/14391226/rr-trace.tar.gz)

I'm at a stage where GDB is still epic wizardry (`edebug`, not so much). No pressure ofc, no warranty expressed or implied :p
I just know that someday these artifacts, `/[^k]traces/` and coredumps, won't be so mysterious, and then perhaps some of the magic will be gone.

**Comment by jamii** [comment]
The recording doesn't work for me, for reasons I don't recognize:

```
> rr replay ./rr-trace                                                                                                                                                                                   rr
Trace XCR0 value 0x7 != our XCR0 value 0x207; Replay will probably fail because glibc dynamic loader examines XCR0

[FATAL src/TraceStream.cc:1160:read_mapped_region() errno: ENOENT] Failed to stat /media/zpool/focus/zig-out/bin/focus-dev: replay is impossible
```

The rr gods are fickle.

---

If you feel like putting more time into this, try first reproducing the crash and then running `coredumpctl dump -r`. That drops you into gdb at the point of the last process crash on your machine and you can poke around.

If that works you can also do `coredumpctl dump -r > dump` and upload both the dump and the focus binary here and then I can try to debug it remotely.

**Comment by antler5** [comment]
> If you feel like putting more time into this

> can also do coredumpctl dump -r > dump and upload both the dump and the focus binary here

I'm feelin' pretty "ah well, we tried ¯\\\_(ツ)\_/¯", but being that it's trivial to [do so](https://github.com/jamii/focus/files/14398757/zig-out.tar.gz)

**Comment by antler5** [comment]
CEASE DEBUGGING

I have a lead, just leave the issue open and I'll get back to you when I have more time

here be demons

**Comment by antler5** [comment]
> CEASE DEBUGGING

I think you knew exactly how to read this, but for clarity:
"Hold up, this is harder to replicate than I thought, don't waste any time before I've checked it out more"

> here be demons

I wasn't able to replicate it on other devices, and my two theories were:
a.) it only replicates on that CPU (demons)
b.) it only replicates over my headless server's yet-unmentioned VNC connection (also potentially demonic, whole 'nother input and display stack)

(Un)fortunately, it's much closer to your initial gut feeling.

> I wonder if the touchpad scroll is fixed to some friendly values.

``` bash
#! /usr/bin/env nix-shell
#! nix-shell -i bash -p bash ydotool
set -xeuo pipefail

export YDOTOOL_SOCKET="/tmp/.ydotool_socket"

PIDS=()
cleanup () {
  for PID in "${PIDS[@]}"; do
    kill -9 "$PID" || true
  done
}
trap cleanup EXIT

sudo ydotoold \
  --socket-path="$YDOTOOL_SOCKET" \
  --socket-own="$UID:0" \
  --keyboard-off &
PIDS+=($!)

# Should probably kill any `focus' background processes before running this.
./zig-out/bin/focus-dev /dev/null &
PIDS+=($!)

# Hopefully `focus' has time to start, and is under the cursor.
sleep 3
until [[ -S "$YDOTOOL_SOCKET" ]] && ydotool debug; do
  sleep 1
done

ydotool mousemove -w -- 0 328
```

328 is the lowest number that reproduces the crash (likely a straightforward overflow, idk) at the default window height, and I believe those scale down together, hence why I was only able to reproduce it over the VNC connection-- it defaults to ~720p or smth. Track-pad acceleration definitely plays a roll in achieving unfriendly values.

**Comment by jamii** [comment]
I wrote in https://www.scattered-thoughts.net/writing/coding/

> An example of getting this wrong is in my text editor: the editor component has [several functions](https://github.com/jamii/focus/blob/62abfa893260001514645d40e0da560d040ddd76/lib/focus/editor.zig#L1189-L1207) for scrolling the viewport that are called from many different places eg if the cursor moves, or the window is resized, or the contents of the buffer are changed from elsewhere.

Finally bit me.

Does https://github.com/jamii/focus/commit/2328def3ad59557361335f2e03d03d265d5399df help?

**Comment by antler5** [comment]
> Does [2328def](https://github.com/jamii/focus/commit/2328def3ad59557361335f2e03d03d265d5399df) help?

Yep!
